/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthenticationRequest } from '../model/models';
import { AuthenticationResponse } from '../model/models';
import { GetTransmissionById400Response } from '../model/models';
import { SignupRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateAuthenticationTokenRequestParams {
    authenticationRequest: AuthenticationRequest;
}

export interface CreateCustomerRequestParams {
    signupRequest: SignupRequest;
}


export interface AuthControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createAuthenticationToken(requestParameters: CreateAuthenticationTokenRequestParams, extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    createCustomer(requestParameters: CreateCustomerRequestParams, extraHttpRequestParams?: any): Observable<object>;

}
